### PR TITLE
Add info section to generators

### PR DESCRIPTION
**Pull request by paulwrath1223**
I was quite confused at first and didn't realize this project had a GitHub because I got it straight from the Fusion360 app store. I just added a little info bubble to the generators, so people can learn what the options do.

image

The link leads to the wiki page for the generator [the baseplate generator uses this](https://github.com/Le0Michine/FusionGridfinityGenerator/wiki/Baseplate-generator-options)

### CODE REVIEW

**Comment by Le0Michine** [comment]
great idea, I'll try to take a look sometime over the weekend

**Comment by Le0Michine** [comment]
just wanted to confirm, does collapsed state get preserved along with other settings when "preserve inputs" radio button is selected? Currently other sections would stay collapsed when window is reopened

**Comment by paulwrath1223** [comment]
I have no idea I didn't read any code, I just looked for the part that
matched what was on-screen. Sorry, I know that's kind of lame.

**Comment by Le0Michine** [comment]
finally got some time to test it, thanks for your contribution!

**Pull request merged**
