### PR TITLE
Extrude skeleton a bit further to fully cutout bottom

### PR DESCRIPTION
**Pull request by jwcoope**
Extrude skeleton a bit more to fully cutout bottom of baseplate, currently skeletonized baseplates have a full bottom, this more closely aligns with typical skeletonized baseplates.

### CODE REVIEW

**Comment by Le0Michine** [comment]
can't reproduce the issue, could you confirm if that's specific to the PR your posted earlier?

**Comment by jwcoope** [comment]
Here's what I'm getting with stock:
image
image
Notice the skeleton is not fully cut through.  Adding the +1cm ensures cut through and you don't end up with a tiny thin line (.25mm in my example case)
image

**Comment by Le0Michine** [comment]
can you try the most resent version from master branch, if cuts all the way through for me, if the issue persists, could you save and share fusion file so I can see what parameters were used?

image

**Comment by Le0Michine** [comment]
closing this since there is no activity, feel free to reopen or create an issue in case the bug persists

**Pull request closed without merging**
